-- C5 (Mac 2026-10-05/06): one durable row per call to the generate proxy (generate-content.js).
--
-- Why: Katie's 09-29 22:30Z tap on the Oct 15 slot left NO trace. 0 generation_attempts and 0
-- generator executions, and the only record that could tell "she didn't press Create" from "the
-- proxy refused" from "n8n's header auth returned 403" was a Netlify function log, probably past
-- retention. generation_attempts is written by the generator, so anything that ends before n8n
-- runs is invisible there. This table is written by the proxy itself.
--
-- Write pattern: the proxy INSERTs the row on entry (in flight: outcome null), awaits that insert
-- before it calls n8n, and PATCHes the outcome before it returns. A row whose outcome stays null
-- IS the signal: the function died (platform timeout, crash) between the two writes.
--
-- Counts and ids only. No post text, prompts, voice, email addresses or response bodies. The ids
-- are as the caller SENT them (uuid-shaped only), because a refusal must record what was asked for;
-- studio_id is verified only when caller_role is set.
--
-- No foreign keys on purpose: a refused call names ids that may not exist, and the trace must
-- never fail because of what it is recording.
--
-- Access: written only by the proxy with the service role. RLS on with no policies, and anon and
-- authenticated get nothing (neither revoke implies the other on Supabase, so both are explicit).

create table public.generate_proxy_calls (
  id uuid primary key,                         -- generated by the proxy, so the PATCH needs no read-back
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- ids as sent (uuid-shaped or null)
  client_request_id uuid,                      -- joins generation_attempts.client_request_id
  studio_id uuid,
  slot_id uuid,
  client_id uuid,
  regenerate_of uuid,

  -- derived by the proxy
  auth_user_id uuid,                           -- GoTrue user id once the session verified
  caller_role text check (caller_role in ('studio_owner', 'studio_instructor')),

  -- counts
  platform_count smallint check (platform_count >= 0),
  posts_requested smallint check (posts_requested >= 0),

  -- outcome. null = in flight, or the function died before the second write.
  outcome text check (outcome in ('refused', 'n8n_response', 'n8n_timeout', 'n8n_network_error')),
  refusal_reason text check (refusal_reason ~ '^[a-z0-9_]{1,48}$'),
  response_status smallint,                    -- what the proxy returned to the browser
  generator_key_sent boolean,                  -- was X-FCA-Proxy-Key attached (never the value)
  forwarded_at timestamptz,                    -- set only if n8n was called
  n8n_status smallint,                         -- n8n's HTTP status, when it answered
  n8n_ms integer check (n8n_ms >= 0),
  duration_ms integer check (duration_ms >= 0),
  completed_at timestamptz,

  -- a refusal always names its reason, and nothing else carries one
  constraint generate_proxy_calls_reason_iff_refused check (
    (outcome = 'refused') = (refusal_reason is not null)
  ),
  -- n8n_status only on a call that reached n8n and got an answer
  constraint generate_proxy_calls_n8n_status_iff_response check (
    (outcome = 'n8n_response') = (n8n_status is not null)
  ),
  -- a refusal never reached n8n
  constraint generate_proxy_calls_refused_not_forwarded check (
    outcome is distinct from 'refused' or forwarded_at is null
  )
);

comment on table public.generate_proxy_calls is
  'C5: one row per generate-content proxy call, written by the proxy before n8n and completed after. Counts and ids only. outcome null = in flight or died.';

create index generate_proxy_calls_created_at_idx on public.generate_proxy_calls (created_at desc);
create index generate_proxy_calls_studio_created_idx on public.generate_proxy_calls (studio_id, created_at desc);
create index generate_proxy_calls_request_idx on public.generate_proxy_calls (client_request_id)
  where client_request_id is not null;
create index generate_proxy_calls_open_idx on public.generate_proxy_calls (created_at)
  where outcome is null;

alter table public.generate_proxy_calls enable row level security;

revoke all on table public.generate_proxy_calls from public;
revoke all on table public.generate_proxy_calls from anon, authenticated;
grant select, insert, update on table public.generate_proxy_calls to service_role;

-- The ids are recorded AS SENT, before authentication: an anonymous caller can put any uuid in
-- them. Attribute a row to a studio or request only when caller_role is not null.
comment on column public.generate_proxy_calls.studio_id is
  'As sent by the caller. Verified only when caller_role is not null.';
comment on column public.generate_proxy_calls.client_request_id is
  'As sent by the caller. Joins generation_attempts.client_request_id; trust only when caller_role is not null.';

-- Retention: none yet (one row per generate tap; low volume). A delete schedule is an open
-- decision, recorded here so the table is not mistaken for one that is pruned.
-- Rollback order: revert the proxy code FIRST, then `drop table public.generate_proxy_calls;`.
-- Dropping the table while the C5 code is live makes every call alert (throttled to 1/min per
-- warm container) and leaves no trace.
