-- Content Calendar WO-2a step 3 — TLK seed, as a data migration (not ad-hoc SQL).
-- Studio 948e26f4-5996-4e11-9b86-c89664b0e600 (The Local Kollective). Seed target authorized
-- for this program by HQ 2026-09-04.
--
-- PROVENANCE. Every value below is traced to a committed document. Where a document does not
-- state a field, the field is left NULL rather than inferred — a seed is a record, and a plausible
-- value substituting for a real one is the failure this program exists to avoid.
--   profile / modalities / partners : build-spec v1.1 Part B WO-2a step 3; v1.0 §3.1; v0.2 §3 rows
--                                     for cadence_target and capture_constraints; v0.2:77 partner list.
--   Q4 2026 program entries         : v0.2 §6.1a (October pair), v0.2:79 (Dec 2 Konnect!),
--                                     v0.2:73 (November Chamber wellness event).
--
-- NOT SEEDED, DELIBERATELY:
--   * September entries (Konnect! Sept 21 Charlotte Hardwick; Events Giveback with Zoe) are Q3,
--     outside the Q4 2026 scope of step 3.
--   * calendar_quarters / calendar_weeks / calendar_slots hold no rows. The quarter arc, its weeks
--     and its ~65 slots are generated by Calendar Quarter Planner in WO-2b step 8. Seeding a
--     skeleton here would be indistinguishable from planner output at assertion time.
--   * v1.0 §3.1 gives soft_slots as an elided example ("[{weekday,early_morning}, ..., {sat,early}]").
--     Only the two entries the document actually names are seeded. The ellipsis is not expanded.
--   * seasonality_priors is NULL: unasked. Not '{}', which would assert "asked, none".

insert into public.calendar_studio_profile
  (studio_id, purpose, audience_exclusions, capture_constraints, cadence_per_week, soft_slots)
values (
  '948e26f4-5996-4e11-9b86-c89664b0e600',
  'community',
  '{}',                                    -- affirmed-empty: asked, none
  array['no filming inside the studio','no phones or cameras','all video owner-controlled'],
  5,
  '[{"day":"weekday","slot":"early_morning"},{"day":"sat","slot":"early"}]'::jsonb
);

insert into public.studio_modalities (studio_id, name) values
  ('948e26f4-5996-4e11-9b86-c89664b0e600','cycling'),
  ('948e26f4-5996-4e11-9b86-c89664b0e600','pilates'),
  ('948e26f4-5996-4e11-9b86-c89664b0e600','core');

insert into public.partners (studio_id, name) values
  ('948e26f4-5996-4e11-9b86-c89664b0e600','SHOP'),
  ('948e26f4-5996-4e11-9b86-c89664b0e600','Recovery Curated'),
  ('948e26f4-5996-4e11-9b86-c89664b0e600','Alorha'),
  ('948e26f4-5996-4e11-9b86-c89664b0e600','Noble Bar'),
  ('948e26f4-5996-4e11-9b86-c89664b0e600','Neat Method'),
  ('948e26f4-5996-4e11-9b86-c89664b0e600','Chamber');

-- Q4 2026 program entries. date_precision per the master calendar as recorded in v0.2 §6.1a.
insert into public.program_entries
  (studio_id, program, title, topic, guest_name, date_precision, event_date, event_month,
   confirmation_status, participants_complete, manual_hold, hold_reason, notes)
values
  -- October Konnect! — the §6.5 / §4.2 per-entry manual hold. Released only by Katie's confirmation.
  ('948e26f4-5996-4e11-9b86-c89664b0e600','konnect',
   'Konnect! — breast cancer screening / mammograms',
   'breast cancer screening / mammograms',
   'Dr. Ringer + Jackie',
   'month', null, '2026-10-01',
   'unconfirmed', false,
   true,
   'Health topic with unconfirmed speakers. Per-entry manual hold (ratified v0.2 §6.5, guard §5.2): no promotional copy until Katie confirms. Not a category rule.',
   'v0.2 §6.1a: "Unconfirmed, speakers carry a question mark, manual hold per §4.2."'),

  -- October Events — highest coordination load on the calendar; three partners simultaneously.
  ('948e26f4-5996-4e11-9b86-c89664b0e600','events',
   'SHOP Fashion Show',
   null, null,
   'month', null, '2026-10-01',
   'unconfirmed', false,
   false, null,
   'Ticketed. Three partners simultaneously (SHOP, Recovery Curated, Alorha) — the case a single partner_id on the entry cannot express (v0.2:79).'),

  -- November Events — existing partner-facing cycling inventory (v0.2:73).
  ('948e26f4-5996-4e11-9b86-c89664b0e600','events',
   'Chamber wellness event',
   null, null,
   'month', null, '2026-11-01',
   'unconfirmed', false,
   false, null,
   'Carries a cycling component ("Cycle/Debi Lynes"). v0.2:73 names it as the cheapest available test of the market-trend hypothesis. Topic and guest not stated in source; left NULL.'),

  -- December Konnect! — the one Q4 entry with a confirmed date.
  ('948e26f4-5996-4e11-9b86-c89664b0e600','konnect',
   'Konnect! roundtable — Alorha',
   null, null,
   'confirmed', '2026-12-02', null,
   'unconfirmed', false,
   false, null,
   'v0.2:79: "Alorha separately headlines the Dec 2 Konnect! roundtable." Date confirmed; topic, guest and participant completeness not stated in source, left NULL / false.');

-- Junction rows. No generated ids hardcoded — resolved by natural key.
insert into public.program_entry_partners (program_entry_id, partner_id)
select pe.id, p.id
from public.program_entries pe
join public.partners p on p.studio_id = pe.studio_id
where pe.studio_id = '948e26f4-5996-4e11-9b86-c89664b0e600'
  and (
    (pe.title = 'SHOP Fashion Show'          and p.name in ('SHOP','Recovery Curated','Alorha')) or
    (pe.title = 'Chamber wellness event'     and p.name = 'Chamber')                             or
    (pe.title = 'Konnect! roundtable — Alorha' and p.name = 'Alorha')
  );
